// ===== Soul Sync — Main JS =====

(function() {
  'use strict';

    // ===== Language Switcher =====
      const langSwitch = document.getElementById('langSwitch');
        const html = document.documentElement;
          let currentLang = localStorage.getItem('soulsync-lang') || 'en';

            function setLang(lang) {
                currentLang = lang;
                    html.setAttribute('lang', lang);
                        html.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
                            localStorage.setItem('soulsync-lang', lang);

                                // Update all elements with data-ar/data-en
                                    document.querySelectorAll('[data-ar][data-en]').forEach(el => {
                                          if (el.tagName === 'META' && el.getAttribute('name') === 'description') {
                                                  el.setAttribute('content', el.getAttribute('data-' + lang));
                                                        } else if (el.tagName === 'TITLE') {
                                                                el.textContent = el.getAttribute('data-' + lang);
                                                                      } else {
                                                                              el.textContent = el.getAttribute('data-' + lang);
                                                                                    }
                                                                                        });

                                                                                            // Update active button
                                                                                                if (langSwitch) {
                                                                                                      langSwitch.querySelectorAll('.lang-btn').forEach(btn => {
                                                                                                              btn.classList.toggle('active', btn.dataset.lang === lang);
                                                                                                                    });
                                                                                                                        }
                                                                                                                          }

                                                                                                                            if (langSwitch) {
                                                                                                                                langSwitch.querySelectorAll('.lang-btn').forEach(btn => {
                                                                                                                                      btn.addEventListener('click', () => setLang(btn.dataset.lang));
                                                                                                                                          });
                                                                                                                                            }

                                                                                                                                              // Init language
                                                                                                                                                setLang(currentLang);

                                                                                                                                                  // ===== Navbar Scroll Effect =====
                                                                                                                                                    const navbar = document.getElementById('navbar');
                                                                                                                                                      if (navbar) {
                                                                                                                                                          window.addEventListener('scroll', () => {
                                                                                                                                                                navbar.classList.toggle('scrolled', window.scrollY > 50);
                                                                                                                                                                    });
                                                                                                                                                                      }

                                                                                                                                                                        // ===== Mobile Menu Toggle =====
                                                                                                                                                                          const mobileToggle = document.getElementById('mobileToggle');
                                                                                                                                                                            const navLinks = document.getElementById('navLinks');
                                                                                                                                                                              if (mobileToggle && navLinks) {
                                                                                                                                                                                  mobileToggle.addEventListener('click', () => {
                                                                                                                                                                                        mobileToggle.classList.toggle('active');
                                                                                                                                                                                              navLinks.classList.toggle('active');
                                                                                                                                                                                                  });

                                                                                                                                                                                                      // Close on link click
                                                                                                                                                                                                          navLinks.querySelectorAll('a').forEach(link => {
                                                                                                                                                                                                                link.addEventListener('click', () => {
                                                                                                                                                                                                                        mobileToggle.classList.remove('active');
                                                                                                                                                                                                                                navLinks.classList.remove('active');
                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                              // ===== Feature Tabs =====
                                                                                                                                                                                                                                                const featureTabs = document.querySelectorAll('.feature-tab');
                                                                                                                                                                                                                                                  const featureContents = document.querySelectorAll('.feature-content');

                                                                                                                                                                                                                                                    featureTabs.forEach(tab => {
                                                                                                                                                                                                                                                        tab.addEventListener('click', () => {
                                                                                                                                                                                                                                                              featureTabs.forEach(t => t.classList.remove('active'));
                                                                                                                                                                                                                                                                    featureContents.forEach(c => c.classList.remove('active'));
                                                                                                                                                                                                                                                                          tab.classList.add('active');
                                                                                                                                                                                                                                                                                const target = document.getElementById(tab.dataset.tab);
                                                                                                                                                                                                                                                                                      if (target) target.classList.add('active');
                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                              // ===== Scroll Animations =====
                                                                                                                                                                                                                                                                                                const observerOptions = { threshold: 0.1, rootMargin: '0px 0px -50px 0px' };
                                                                                                                                                                                                                                                                                                  const observer = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                      entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                            if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                    entry.target.classList.add('visible');
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                }, observerOptions);

                                                                                                                                                                                                                                                                                                                                  document.querySelectorAll('.product-card, .pricing-card, .layer, .about-card, .help-card').forEach(el => {
                                                                                                                                                                                                                                                                                                                                      observer.observe(el);
                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                          // ===== Smooth Scroll =====
                                                                                                                                                                                                                                                                                                                                            document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                                                                                                                                                                                                                                                                                                                                                anchor.addEventListener('click', function(e) {
                                                                                                                                                                                                                                                                                                                                                      const href = this.getAttribute('href');
                                                                                                                                                                                                                                                                                                                                                            if (href === '#') return;
                                                                                                                                                                                                                                                                                                                                                                  const target = document.querySelector(href);
                                                                                                                                                                                                                                                                                                                                                                        if (target) {
                                                                                                                                                                                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                      // ===== Active Nav Link =====
                                                                                                                                                                                                                                                                                                                                                                                                        const sections = document.querySelectorAll('section[id]');
                                                                                                                                                                                                                                                                                                                                                                                                          const navLinkEls = document.querySelectorAll('.nav-link[href^="#"]');

                                                                                                                                                                                                                                                                                                                                                                                                            window.addEventListener('scroll', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                let current = '';
                                                                                                                                                                                                                                                                                                                                                                                                                    sections.forEach(section => {
                                                                                                                                                                                                                                                                                                                                                                                                                          const sectionTop = section.offsetTop - 150;
                                                                                                                                                                                                                                                                                                                                                                                                                                if (window.scrollY >= sectionTop) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        current = section.getAttribute('id');
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                      navLinkEls.forEach(link => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            link.classList.toggle('active', link.getAttribute('href') === '#' + current);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // ===== Parallax Orbs (Mouse) =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const orbs = document.querySelectorAll('.orb');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let mouseX = 0, mouseY = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let orbX = 0, orbY = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.addEventListener('mousemove', (e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mouseX = (e.clientX / window.innerWidth - 0.5) * 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mouseY = (e.clientY / window.innerHeight - 0.5) * 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function animateOrbs() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            orbX += (mouseX - orbX) * 0.02;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                orbY += (mouseY - orbY) * 0.02;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    orbs.forEach((orb, i) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const speed = (i + 1) * 15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                orb.style.transform = `translate(${orbX * speed}px, ${orbY * speed}px) scale(${1 + Math.abs(orbX) * 0.05})`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        requestAnimationFrame(animateOrbs);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (orbs.length > 0) animateOrbs();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // ===== Animated Pricing Bars =====
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const pricingBars = document.querySelectorAll('.mini-bar div');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const pricingObserver = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      entries.forEach(entry => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (entry.isIntersecting) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const bar = entry.target;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const width = bar.style.width;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    bar.style.width = '0';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setTimeout(() => { bar.style.width = width; }, 200);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }, { threshold: 0.5 });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pricingBars.forEach(bar => pricingObserver.observe(bar));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })();